# Exercícios de Numpy

### Importação

In [2]:
import numpy as np
from numpy.random import default_rng

rng = default_rng()

### Função linha()

In [5]:
def linha():
    print('-'*30)

### 1 - Crie uma matriz NumPy 4x4 com números inteiros aleatórios entre 1 e 10.

In [3]:
matriz = rng.integers(low=1, high=10, size=(4,4))
print(matriz)

[[9 5 3 1]
 [3 4 1 2]
 [9 9 8 9]
 [5 3 1 5]]


### 2 - Calcule a média de cada linha e de cada coluna da matriz criada no exercício 1.

In [ ]:
matriz = rng.integers(low=1, high=10, size=(4,4))
print(matriz)
linha()
media_matriz_linha = np.mean(matriz, axis=1) # axis=1 é para cada linha
print(media_matriz_linha)
linha()
media_matriz_coluna = np.mean(matriz, axis=0) # axis=0 é para cada coluna
print(media_matriz_coluna)

[[1 3 9 7]
 [5 6 3 4]
 [4 4 1 8]
 [5 8 4 9]]
------------------------------
[5.   4.5  4.25 6.5 ]
------------------------------
[3.75 5.25 4.25 7.  ]


### 3 - Remodele a matriz do exercício 1 em uma matriz 2x8.

In [6]:
rng = default_rng()
matriz = rng.integers(low=1, high=10, size=(4,4))
print(matriz)
linha()
nova_matriz = np.reshape(matriz, (2,8))
print(nova_matriz)

[[1 8 4 8]
 [4 8 9 7]
 [9 1 4 4]
 [5 2 8 2]]
------------------------------
[[1 8 4 8 4 8 9 7]
 [9 1 4 4 5 2 8 2]]


### 4 - Extraia todos os elementos da matriz no exercício 1 que sejam maiores que 5.

In [7]:
rng = default_rng()
matriz = rng.integers(low=1, high=10, size=(4,4))
print(matriz)
linha()
matriz_maior5 = matriz[matriz>5]
print(matriz_maior5)

[[6 4 9 7]
 [2 4 4 2]
 [4 9 2 7]
 [3 1 6 3]]
------------------------------
[6 9 7 9 7 6]


### 5 - Crie duas matrizes NumPy do mesmo formato e execute adição, subtração, multiplicação e divisão elemento a elemento.

In [8]:
rng = default_rng()
matriz1 = rng.integers(low=1, high=10, size=(4,4))
matriz2 = rng.integers(low=1, high=10, size=(4,4))

#### soma | np.add()

In [9]:
print(matriz1 + matriz2) # np.add()
linha()

[[11 15 14  9]
 [ 8 16  6 14]
 [ 9  6 14  6]
 [ 2  8  6 11]]
------------------------------


#### subtração | np.subtract()

In [10]:
print(matriz1 - matriz2) # np.subtract()
linha()

[[ 5  3 -2 -7]
 [ 0  2  2  4]
 [ 3 -2 -2  4]
 [ 0  4 -2 -1]]
------------------------------


#### multiplicação | np.multiply()

In [11]:
print(matriz1 * matriz2) # np.multiply()
linha()

[[24 54 48  8]
 [16 63  8 45]
 [18  8 48  5]
 [ 1 12  8 30]]
------------------------------


#### divisão | np.divide()

In [12]:
print(matriz1 / matriz2) # np.divide()
linha()

[[2.66666667 1.5        0.75       0.125     ]
 [1.         1.28571429 2.         1.8       ]
 [2.         0.5        0.75       5.        ]
 [1.         3.         0.5        0.83333333]]
------------------------------
